name: pub_stats
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # TODO: Remove these
  fast_rx_flutter: ^0.1.3
  fast_rx_persistence: ^0.3.0
  fast_rx_shared_preferences: ^0.1.5
  fast_overlays: ^0.1.5
  fast_nav: ^0.4.1

  get_it: ^8.0.2
  logger: ^2.0.2+1
  intl: ^0.20.2
  get_time_ago: ^2.0.0
  font_awesome_flutter: ^10.0.0-beta
  url_launcher: ^6.0.17
  fl_chart: ^1.0.0
  flutter_svg: ^2.0.0+1
  pub_api_client: ^3.1.1

  pub_stats_core:
    path: ../pub_stats_core

  # Firebase
  firebase_core: ^4.1.0
  firebase_analytics: ^12.0.1
  firebase_app_check: ^0.4.0+1
  firebase_auth: ^6.0.2
  firebase_database: ^12.0.1
  firebase_performance: ^0.11.0+1

  collection: ^1.16.0
  recase: ^4.1.0
  firebase_ui_database: ^2.0.0
  sliver_tools: ^0.2.12
  web: ^1.1.0
  platform_plus: ^4.8.1
  meta: ^1.16.0

dev_dependencies:
  rexios_lints: ^15.0.0
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: ../resources/logo.png
  android: false
  ios: false
